<a href="https://colab.research.google.com/github/talhabinazmat21/Deep_Learning/blob/main/tensors_and_variables/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [22]:
x1 = tf.constant([
    [
        [1,2,3,4],
        [2,45,232,1],
        [1,2,3,4],
        [2,45,232,1]
    ],
    [
        [1,2,3,4],
        [2,45,232,1],
        [1,2,3,4],
        [2,45,232,1]
    ],
    [
        [1,2,3,4],
        [2,45,232,1],
        [1,2,3,4],
        [2,45,232,1]
    ],
    [
        [1,2,3,4],
        [2,45,232,1],
        [1,2,3,4],
        [2,45,232,1]
    ]
], dtype = tf.float32)

x2 = tf.constant([
    [
        [3,5,6,23],
        [3,2,65,7]
    ],
    [
        [3,5,6,23],
        [3,2,65,7]
    ],
    [
        [3,5,6,23],
        [3,2,65,7]
    ],
    [
        [3,5,6,23],
        [3,2,65,7]
    ]
], dtype = tf.float32)

print(tf.linalg.matmul(x2,x1))

tf.Tensor(
[[[  65. 1278. 6523.   64.]
  [  86.  541. 2292.  281.]]

 [[  65. 1278. 6523.   64.]
  [  86.  541. 2292.  281.]]

 [[  65. 1278. 6523.   64.]
  [  86.  541. 2292.  281.]]

 [[  65. 1278. 6523.   64.]
  [  86.  541. 2292.  281.]]], shape=(4, 2, 4), dtype=float32)


In [12]:
x3 = tf.constant([
    [
        [1,2,3,4],
        [2,45,232,1],
        [1,2,3,4],
        [2,45,232,1]
    ],
    [
        [1,2,3,4],
        [2,45,232,1],
        [1,2,3,4],
        [2,45,232,1]
    ],
    [
        [1,2,3,4],
        [2,45,232,1],
        [1,2,3,4],
        [2,45,232,1]
    ]
])

x4 = tf.constant([
    [
        [3,5,6,23],
        [3,2,65,7]
    ],
    [
        [3,5,6,23],
        [3,2,65,7]
    ],
    [
        [3,5,6,23],
        [3,2,65,7]
    ]
])

print(x4@x3)



tf.Tensor(
[[[  65 1278 6523   64]
  [  86  541 2292  281]]

 [[  65 1278 6523   64]
  [  86  541 2292  281]]

 [[  65 1278 6523   64]
  [  86  541 2292  281]]], shape=(3, 2, 4), dtype=int32)


In [14]:
print(x1)
print(tf.transpose(x1))

tf.Tensor(
[[[  1   2   3   4]
  [  2  45 232   1]
  [  1   2   3   4]
  [  2  45 232   1]]

 [[  1   2   3   4]
  [  2  45 232   1]
  [  1   2   3   4]
  [  2  45 232   1]]

 [[  1   2   3   4]
  [  2  45 232   1]
  [  1   2   3   4]
  [  2  45 232   1]]], shape=(3, 4, 4), dtype=int32)
tf.Tensor(
[[[  1   1   1]
  [  2   2   2]
  [  1   1   1]
  [  2   2   2]]

 [[  2   2   2]
  [ 45  45  45]
  [  2   2   2]
  [ 45  45  45]]

 [[  3   3   3]
  [232 232 232]
  [  3   3   3]
  [232 232 232]]

 [[  4   4   4]
  [  1   1   1]
  [  4   4   4]
  [  1   1   1]]], shape=(4, 4, 3), dtype=int32)



Sparse matrices are a type of matrix in which most of the elements are zero. They are distinct from dense matrices, where most of the elements are non-zero. Sparse matrices are particularly useful in scenarios where large amounts of data are mostly zeros, as they allow for significant improvements in storage efficiency and computational performance.

Why Use Sparse Matrices?
Memory Efficiency: Storing only the non-zero elements of sparse matrices saves memory, which is beneficial when dealing with large datasets or matrices where the non-zero elements are few.
Computational Efficiency: Operations such as multiplication or inversion can be faster on sparse matrices since calculations involving zero elements can be skipped.
Representation of Sparse Matrices
Sparse matrices can be represented in various formats, each optimizing different operations. Some common formats include:

Compressed Sparse Row (CSR): Stores the non-zero values consecutively along with arrays for indices and row pointers. This format is efficient for row slicing and matrix-vector multiplication.
Compressed Sparse Column (CSC): Similar to CSR but stores data column-wise. It is efficient for column slicing and other column-wise operations.
Coordinate List (COO): Stores a list of (row, column, value) tuples. It is particularly useful for constructing sparse matrices incrementally as data can be added in any order.
Applications of Sparse Matrices
Sparse matrices are extensively used in various fields such as:

Scientific Computing: In simulations and calculations involving large-scale systems, many of which have sparse characteristics.
Machine Learning and Data Mining: In algorithms that involve large datasets, especially in natural language processing and recommendation systems.
Graph Algorithms: In the representation of adjacency matrices for graphs, where most connections between nodes are absent (i.e., zero).
Image Processing and Computer Vision: In scenarios involving image transformations where many values can be zero due to the nature of the transformation or filtering applied