<a href="https://colab.research.google.com/github/talhabinazmat21/Deep_Learning/blob/main/tensors_and_variables/Math_functions_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tensor_2d = tf.constant([[2,3,4,-5,-6,-0.6],
                         [1,3,5,6,-7,-8],
                         [-0.3,-0.5,-0.6,-0.9,-6, 4]])
tensor_2d_abs = tf.math.abs(tensor_2d)
print(tensor_2d_abs)

### abs converts all the negative numbvers to positive and keeps the positive numbers positive

tf.Tensor(
[[2.  3.  4.  5.  6.  0.6]
 [1.  3.  5.  6.  7.  8. ]
 [0.3 0.5 0.6 0.9 6.  4. ]], shape=(3, 6), dtype=float32)


In [ ]:
tensor_2d_complex = tf.constant([[2 + 3j,3 - 8j ,4,-5,-6 -0.2j,-0.6],
                         [1,3,5,6,-7 + 4j,-8],
                         [-0.3 + 2j,-0.5,-0.6,-0.9,-6 + 0.1j, 4]])
tensor_2d_complex_abs = tf.math.abs(tensor_2d_complex)
print(tensor_2d_complex_abs)

## also takes the absolute of complex numbers using the sqrt(a.a + b.b) formula

tf.Tensor(
[[3.60555128 8.54400375 4.         5.         6.00333241 0.6       ]
 [1.         3.         5.         6.         8.06225775 8.        ]
 [2.02237484 0.5        0.6        0.9        6.00083328 4.        ]], shape=(3, 6), dtype=float64)


In [39]:
complex_number_1 = tensor_2d_complex[0,0]
print(complex_number_1)





tf.Tensor((2+3j), shape=(), dtype=complex128)


In [37]:
abs_complex_number_1 = tf.sqrt((tf.constant(2, dtype = tf.float32))**2 + (tf.constant(3, dtype = tf.float32))**2)
print(abs_complex_number_1)

## as you can see that the value printed is the same as the value printed in the absolute matrix. Simple numbers inmput wont work
## int he case of the sqrt inmput as they are not tensorflow dtypes so every number given as input to the tf fucntions should be a
## a tf datatype


tf.Tensor(3.6055512, shape=(), dtype=float32)


In [38]:
x1 = tf.constant([1,2,3,4,5,6], dtype = tf.int32)
x2 = tf.constant([6,5,4,3,2,1], dtype = tf.int32)
print(tf.math.divide(x1,x2))


## both numebr should have the same datatype. or else it would not work. Also now lets try now to actually do some thing different.

x3 = tf.constant([1,2,3,0,5,0], dtype = tf.int32)
print(tf.math.divide(x1,x3))
print(tf.math.divide_no_nan(x1,x3))


## If i use the funciton divide_no_nan then there would be no infinities shown and infinity would be mapped to a zero

tf.Tensor([0.16666667 0.4        0.75       1.33333333 2.5        6.        ], shape=(6,), dtype=float64)
tf.Tensor([ 1.  1.  1. inf  1. inf], shape=(6,), dtype=float64)
tf.Tensor([1. 1. 1. 0. 1. 0.], shape=(6,), dtype=float64)


In [51]:
x4 = tf.constant([
                  [
                      [[1,2,3,4,5],
                      [2,3,4,5,6]],

                      [[1,2,3,4,5],
                      [2,3,4,5,6]]
                  ],

                  [
                    [[1,2,3,4,5],
                    [2,3,4,5,6]],

                    [[1,2,3,4,5],
                    [2,3,4,5,6]]
                  ],

                 [
                    [[1,2,3,4,5],
                    [2,3,4,5,6]],

                    [[1,2,3,4,5],
                    [2,3,4,5,6]]
                  ],

                 [
                     [[1,2,3,4,5],
                    [2,3,4,5,6]],

                    [[1,2,3,4,5],
                    [2,3,4,5,6]]]
                ], dtype = tf.float32)

## This is a 4d matrix. Lets do some add operations with it

x5 = tf.constant([
     [
         [
            [5,4,3,2,1],
            [5,4,3,2,1]
          ],
                  [
            [5,4,3,2,1],
            [5,4,3,2,1]
          ],
      ],
      [
         [
            [5,4,3,2,1],
            [5,4,3,2,1]
          ],
                  [
            [5,4,3,2,1],
            [5,4,3,2,1]
          ],
      ],
      [
         [
            [5,4,3,2,1],
            [5,4,3,2,1]
          ],
                  [
            [5,4,3,2,1],
            [5,4,3,2,1]
          ],
      ],
      [
         [
            [5,4,3,2,1],
            [5,4,3,2,1]
          ],
                  [
            [5,4,3,2,1],
            [5,4,3,2,1]
          ],
      ],
    ], dtype = tf.float32)

print(tf.math.add(x4,x5))

x6 = tf.constant(10, dtype = tf.float32)

print(tf.math.add(x5,x6))

tf.Tensor(
[[[[6. 6. 6. 6. 6.]
   [7. 7. 7. 7. 7.]]

  [[6. 6. 6. 6. 6.]
   [7. 7. 7. 7. 7.]]]


 [[[6. 6. 6. 6. 6.]
   [7. 7. 7. 7. 7.]]

  [[6. 6. 6. 6. 6.]
   [7. 7. 7. 7. 7.]]]


 [[[6. 6. 6. 6. 6.]
   [7. 7. 7. 7. 7.]]

  [[6. 6. 6. 6. 6.]
   [7. 7. 7. 7. 7.]]]


 [[[6. 6. 6. 6. 6.]
   [7. 7. 7. 7. 7.]]

  [[6. 6. 6. 6. 6.]
   [7. 7. 7. 7. 7.]]]], shape=(4, 2, 2, 5), dtype=float32)
tf.Tensor(
[[[[15. 14. 13. 12. 11.]
   [15. 14. 13. 12. 11.]]

  [[15. 14. 13. 12. 11.]
   [15. 14. 13. 12. 11.]]]


 [[[15. 14. 13. 12. 11.]
   [15. 14. 13. 12. 11.]]

  [[15. 14. 13. 12. 11.]
   [15. 14. 13. 12. 11.]]]


 [[[15. 14. 13. 12. 11.]
   [15. 14. 13. 12. 11.]]

  [[15. 14. 13. 12. 11.]
   [15. 14. 13. 12. 11.]]]


 [[[15. 14. 13. 12. 11.]
   [15. 14. 13. 12. 11.]]

  [[15. 14. 13. 12. 11.]
   [15. 14. 13. 12. 11.]]]], shape=(4, 2, 2, 5), dtype=float32)


In [53]:
print(tf.math.multiply(x4,x5))
print(tf.math.multiply(x5, x6))

tf.Tensor(
[[[[ 5.  8.  9.  8.  5.]
   [10. 12. 12. 10.  6.]]

  [[ 5.  8.  9.  8.  5.]
   [10. 12. 12. 10.  6.]]]


 [[[ 5.  8.  9.  8.  5.]
   [10. 12. 12. 10.  6.]]

  [[ 5.  8.  9.  8.  5.]
   [10. 12. 12. 10.  6.]]]


 [[[ 5.  8.  9.  8.  5.]
   [10. 12. 12. 10.  6.]]

  [[ 5.  8.  9.  8.  5.]
   [10. 12. 12. 10.  6.]]]


 [[[ 5.  8.  9.  8.  5.]
   [10. 12. 12. 10.  6.]]

  [[ 5.  8.  9.  8.  5.]
   [10. 12. 12. 10.  6.]]]], shape=(4, 2, 2, 5), dtype=float32)
tf.Tensor(
[[[[50. 40. 30. 20. 10.]
   [50. 40. 30. 20. 10.]]

  [[50. 40. 30. 20. 10.]
   [50. 40. 30. 20. 10.]]]


 [[[50. 40. 30. 20. 10.]
   [50. 40. 30. 20. 10.]]

  [[50. 40. 30. 20. 10.]
   [50. 40. 30. 20. 10.]]]


 [[[50. 40. 30. 20. 10.]
   [50. 40. 30. 20. 10.]]

  [[50. 40. 30. 20. 10.]
   [50. 40. 30. 20. 10.]]]


 [[[50. 40. 30. 20. 10.]
   [50. 40. 30. 20. 10.]]

  [[50. 40. 30. 20. 10.]
   [50. 40. 30. 20. 10.]]]], shape=(4, 2, 2, 5), dtype=float32)


In [76]:
x7 = tf.constant([5,2,6,6,4,6], dtype = tf.float32)
x8 = tf.constant ([[7],[5], [3]], dtype= tf.float32)
print(tf.shape(x7))
print(tf.shape(x8))
print(tf.math.multiply(x8,x7))


x9 = tf.constant([5,2,6,6,4,6], dtype = tf.float32)
x10 = tf.constant ([[7,2],[5,6], [3,2]], dtype= tf.float32)
print(tf.shape(x9))
print(tf.shape(x10))
##print(tf.math.multiply(x9,x10))|

tf.Tensor([6], shape=(1,), dtype=int32)
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor(
[[35. 14. 42. 42. 28. 42.]
 [25. 10. 30. 30. 20. 30.]
 [15.  6. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)
tf.Tensor([6], shape=(1,), dtype=int32)
tf.Tensor([3 2], shape=(2,), dtype=int32)


In TensorFlow, operations such as tf.math.multiply (which corresponds to element-wise multiplication) rely on specific rules regarding the shapes of the tensors involved. Understanding these rules can help explain why the multiplication of x7 and x8 works, but that of x9 and x10 does not.

Case 1: Multiplying x7 and x8
x7 has a shape of [6] (a 1D tensor with 6 elements).
x8 has a shape of [3, 1] (a 2D tensor with 3 rows and 1 column).
TensorFlow can broadcast these shapes against each other. The broadcasting rules allow these shapes to align by implicitly expanding the dimensions:

x7 becomes [1, 6]
x8 remains [3, 1]
Through broadcasting:

x8 will be expanded to [3, 6] (repeating its columns)
x7 will be expanded to [3, 6] (repeating its rows)
The result is a [3, 6] matrix where each row of x8 multiplies element-wise across each row of x7.

Case 2: Multiplying x9 and x10
x9 has a shape of [6] (the same 1D tensor as x7).
x10 has a shape of [3, 2] (a 2D tensor with 3 rows and 2 columns).
When TensorFlow attempts to broadcast these shapes:

x9 can be treated as [1, 6] (adding a leading dimension).
x10 is [3, 2].
Here, the second dimension conflicts:

The second dimension of x9 (treated as [1, 6]) is 6.
The second dimension of x10 is 2.
Since 6 does not match 2 and neither is 1, TensorFlow cannot broadcast these arrays in a way that aligns them for element-wise multiplication, resulting in an error.

Broadcasting requires that the dimensions of both tensors either match or one of them is 1. In the case of x9 and x10, this rule is violated, so the operation fails. To successfully perform the operation, the dimensions must be compatible either through reshaping or by adjusting the sizes so that they align correctly.


In [83]:
# these functions will print the index of maximum number ina tensor
print(tf.math.argmax(x9))
print(tf.math.argmin(x9))

print(tf.math.argmax(x5, axis = 3))





tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]], shape=(4, 2, 2), dtype=int64)


In [84]:
print(tf.pow(x4, x5))

##makes the elements of the second matrix power of the elements of the first matrix

tf.Tensor(
[[[[ 1. 16. 27. 16.  5.]
   [32. 81. 64. 25.  6.]]

  [[ 1. 16. 27. 16.  5.]
   [32. 81. 64. 25.  6.]]]


 [[[ 1. 16. 27. 16.  5.]
   [32. 81. 64. 25.  6.]]

  [[ 1. 16. 27. 16.  5.]
   [32. 81. 64. 25.  6.]]]


 [[[ 1. 16. 27. 16.  5.]
   [32. 81. 64. 25.  6.]]

  [[ 1. 16. 27. 16.  5.]
   [32. 81. 64. 25.  6.]]]


 [[[ 1. 16. 27. 16.  5.]
   [32. 81. 64. 25.  6.]]

  [[ 1. 16. 27. 16.  5.]
   [32. 81. 64. 25.  6.]]]], shape=(4, 2, 2, 5), dtype=float32)
