<a href="https://colab.research.google.com/github/talhabinazmat21/Deep_Learning/blob/main/tensors_and_variables/sparse_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf
sparse_tensor = tf.sparse.SparseTensor(
    indices = [[1,2], [5,4]], values = [12, 45], dense_shape = [8,8]
)

print(sparse_tensor)


print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[1 2]
 [5 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([12 45], shape=(2,), dtype=int32), dense_shape=tf.Tensor([8 8], shape=(2,), dtype=int64))
tf.Tensor(
[[ 0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]], shape=(8, 8), dtype=int32)
